---
- name: Oracle Database Automation 584
  hosts: all
  vars:
    ansible_remote_tmp: /tmp
    txt_output: ""
    output_path: /tmp/out1.txt # Enter the output path 
  become: yes
  tasks:
    - name: Set content for txt file
      set_fact:
        txt_output: "{{ txt_output }}\n\n\n\n Server Name : {{ inventory_hostname }}"

    - name: Execute disk utilization status command
      shell: |
        df -h
      register: disk_utlization
     
      ignore_errors: yes

    - name: Set content for txt file
      set_fact:
        txt_output: "{{ txt_output }}\n\n\n\nDisk Utilization Status :\n{{ disk_utlization.stdout_lines | join('\n') }}"
      
    
    - name: Execute memory status command
      shell: |
        free -h
      register: memory_utlisation
     
      ignore_errors: yes

    - name: Set content for txt file
      set_fact:
        txt_output: "{{ txt_output }}\n\n\n\nMemory Utilization Status Command :\n{{ memory_utlisation.stdout_lines | join('\n') }}"
      

    - name: display data
      debug:
        msg: "{{ txt_output }}"
     

    - name: Write all content to output_file.txt
      lineinfile:
        line: "{{ txt_output }}"
        path: "{{ output_path }}"
        create: yes
      delegate_to: 10.127.136.172
