---
- name: Oracle Database Automation 584
  hosts: all  # here you can add your target server
  vars:
    ansible_remote_tmp: /tmp
    txt_output: ""
    output_path: /tmp/out1.txt #Enter the output path 
  become: yes
  # become_user: oracle
  # become_flags: -i
  tasks:
    - name: Execute disk utilization status command #16
      shell: |
        df -h
      register: disk_utlization
      delegate_to: "{{ inventory_hostname }}"

    - name: Set content for txt file
      set_fact:
        txt_output: "{{ txt_output }}\n\n\n\nDisk Utilization Status Command:\n{{ disk_utlization.stdout_lines | join('\n') }}"
      delegate_to: "{{ inventory_hostname }}"
    
    - name: Execute memory status command #16
      shell: |
        free -h
      register: memory_utlisation
      delegate_to: "{{ inventory_hostname }}"

    - name: Set content for txt file
      set_fact:
        txt_output: "{{ txt_output }}\n\n\n\nMemory Utilization Status Command:\n{{ memory_utlisation.stdout_lines | join('\n') }}"
      delegate_to: "{{ inventory_hostname }}"

 
       

    - name: Write all content to output_file.txt
      copy:
        content: "{{ txt_output }}"
        dest: "{{ output_path }}"
      delegate_to: 10.127.136.172

      
