---
- name: Oracle Database Automation 584
  hosts: all
  vars:
    ansible_remote_tmp: /tmp
    txt_output: ""
    output_path: /tmp/out1.txt # Enter the output path 
  become: yes
  tasks:
    - name: Execute disk utilization status command
      shell: |
        df -h
      register: disk_utlization
      delegate_to: "{{ inventory_hostname }}"
      ignore_errors: yes

    - name: Set content for txt file
      set_fact:
        txt_output: "{{ txt_output }}\n\n\n\nDisk Utilization Status Command for {{ inventory_hostname }}:\n{{ disk_utlization.stdout_lines | join('\n') }}"
      delegate_to: "{{ inventory_hostname }}"
    
    - name: Execute memory status command
      shell: |
        free -h
      register: memory_utlisation
      delegate_to: "{{ inventory_hostname }}"
      ignore_errors: yes

    - name: Set content for txt file
      set_fact:
        txt_output: "{{ txt_output }}\n\n\n\nMemory Utilization Status Command for {{ inventory_hostname }}:\n{{ memory_utlisation.stdout_lines | join('\n') }}"
      delegate_to: "{{ inventory_hostname }}"

    - name: display data
      debug:
        msg: "{{ txt_output }}"
      delegate_to: "{{ inventory_hostname }}"

    - name: Write all content to output_file.txt
      lineinfile:
        line: "{{ txt_output }}"
        path: "{{ output_path }}"
        create: yes
      delegate_to: 10.127.136.172
