---
- name: test playbook
  hosts: all
  become: true
  gather_facts: true
  tasks:
   - name: check free space 
     command: free
     register: free_space
   - name: append output to a file
     lineinfile:
       line: "{{ free_space.stdout }}"
       dest: "output.txt"
       insertafter: EOF
