---
- name: test playbook
  hosts: all
  gather_facts: true
  tasks:
    - name: check free space 
      command: free
      register: free_space
      delegate_to: "{{ inventory_hostname }}"
      ignore_errors: yes

    - name: store free space output in a variable
      set_fact:
        free_space_output: "{{ free_space.stdout }}"

    - debug:
        var: free_space_output
