---
- name: test playbook
  hosts: all
  gather_facts: true
  tasks:
    - name: check free space 
      command: free
      register: free_space
      delegate_to: "{{ inventory_hostname }}"
      ignore_errors: yes

    - name: cat /proc/meminfo
      command: cat /proc/meminfo
      register: meminfo_output
      delegate_to: "{{ inventory_hostname }}"
      ignore_errors: yes


    - name: store free space output in a variable
      set_fact:
        combined_output: "{{ free_space_output | default([]) + [meminfo_output.stdout | default('')] }}"

    - debug:
        var: combined_output
