---
- name: test playbook
  hosts: all
  gather_facts: true
  tasks:
    - name: check free space 
      command: free
      register: free_space
      delegate_to: "{{ inventory_hostname }}"
      ignore_errors: yes
    - name: append output to a file on localhost
      local_action:
        module: lineinfile
        path: /home/ec2-user/output_file
        line: "{{ free_space.stdout }}"
      delegate_to: localhost
