- name: test playbook
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: check free space 
      command: free
      register: free_space
      delegate_to: "{{ inventory_hostname }}"
      ignore_errors: yes

    - name: cat /proc/meminfo
      command: df -h
      register: meminfo_output
      delegate_to: "{{ inventory_hostname }}"
      ignore_errors: yes

    # - name: store free space output in a variable with server name
    #   set_fact:
    #     combined_output: "{{ combined_output | default({}) | combine({inventory_hostname: free_space.stdout + '\n' + meminfo_output.stdout}) }}"
    #   delegate_to: localhost
    - name: store free space output in a variable with server name
      set_fact:
        combined_output: "{{ combined_output | default({}) | combine({inventory_hostname: (free_space.stdout | default('') ~ '\n' ~ meminfo_output.stdout | default(''))}) }}"
      delegate_to: localhost


    - debug:
        var: combined_output

