---  
- name: Check CPU Utilization and Send Email
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get CPU Utilization
      win_shell: Get-WmiObject Win32_Processor | Measure-Object -Property LoadPercentage -Average | Select-Object Average
      register: cpu_utilization

    - name: Debug Print CPU Utilization
      debug:
        var: cpu_utilization.stdout_lines

   
      

