---
- name: Check CPU Utilization and Send Email
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get input for session details
      vars_prompt:
        - name: sid
          prompt: "Enter SID"
          private: no
        - name: serial
          prompt: "Enter Serial#"
          private: no
        - name: inst_id
          prompt: "Enter Instance ID"
          private: no
