---
- name: test playbook
  hosts: all
  become: true
  gather_facts: true
  tasks:
   - name: check free space 
     command: free
     register: free_space
   - name: write output to file
     lineinfile:
       line: "{{ free_space.stdout }}"
       dest: "/home/output_file"
       insertafter: EOF
